### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by MAYALURI-ANUSHA** [LanguageTranslationOrg/LanguageTranslationSystem#23]
@jeshtha2003 

Design a logo and finalize it after discussing with team

**Comment by jeshtha2003** [comment]
![Sniglet (3)](https://github.com/LanguageTranslationOrg/LanguageTranslationSystem/assets/142726417/42b9bf6b-c782-47ad-a0d3-6d70d0e11c80)
This is update logo according to decided theme.
