### ISSUE TITLE
Test case development - sharing & copy feature

### ISSUE THREAD

**Issue by springboardmentor131** [LanguageTranslationOrg/LanguageTranslationSystem#28]
Develop test case document for social media sharing feature & copy feature

**Comment by Kumaramitabh** [comment]
[Test.Cases.for.Sharing.Copying.docx](https://github.com/user-attachments/files/16028934/Test.Cases.for.Sharing.Copying.docx)

**Comment by Kumaramitabh** [comment]
[Test.Cases.for.Sharing.Copying (1).docx](https://github.com/user-attachments/files/16043774/Test.Cases.for.Sharing.Copying.1.docx)
