### ISSUE TITLE
Validations & Error Handling

### ISSUE THREAD

**Issue by MAYALURI-ANUSHA** [LanguageTranslationOrg/LanguageTranslationSystem#32]
Write validations and include in the code like whether the user entered the text or not, selected languages or not etc
and also write code to handle errors.

Note: Create a branch and then work on your code, don't directly commit to the main branch

**Comment by BBB2912** [comment]
if any errors arise in translation page or model loading page it can display like this 👍🏽 
![Screenshot 2024-06-28 171805](https://github.com/LanguageTranslationOrg/LanguageTranslationSystem/assets/125733485/4fdab9b7-f120-438d-be90-05562175cd58)

**Comment by BBB2912** [comment]
If any server side error may arraise it can show FLASK ERROR 👍🏽 
![Uploading Screenshot 2024-06-28 172602.png…]()

**Comment by BBB2912** [comment]
if user forgot enter text it can show warning like this:
![Screenshot 2024-06-28 172046](https://github.com/LanguageTranslationOrg/LanguageTranslationSystem/assets/125733485/3d4088f0-a9d2-4862-8058-4a00bee6ae4a)

**Comment by BBB2912** [comment]
it can also check wheather selected text and enterning text are same or not :
![Screenshot 2024-06-28 181642](https://github.com/LanguageTranslationOrg/LanguageTranslationSystem/assets/125733485/8fad766c-c95a-4eb6-bad9-bb4e0a1a0185)

**Comment by BBB2912** [comment]
here we can validate character limit if limit is exceeded it can show warning linke this:
![Screenshot 2024-06-28 181943](https://github.com/LanguageTranslationOrg/LanguageTranslationSystem/assets/125733485/45854ac9-d144-42a8-aa3e-869482cb32d1)

**Comment by BBB2912** [comment]
i was added all validations and warning popups
