### ISSUE TITLE
Testing - home page

### ISSUE THREAD

**Issue by MAYALURI-ANUSHA** [LanguageTranslationOrg/LanguageTranslationSystem#39]
Home page should be tested based on the test cases developed by the team

@arpita2506
@sandeepkumar-v01

**Comment by arpita2506** [comment]
Testing is done .Now we have to update the results.

**Comment by arpita2506** [comment]
[Testing_Result_Home Page.xlsx](https://github.com/user-attachments/files/16106407/Testing_Result_Home.Page.xlsx)
Testing of home page is done and the result is in the excel file according to the test cases of the home page uploaded in docs folder in word file.

**Comment by MAYALURI-ANUSHA** [comment]
Testing Home page is successfully completed
