### ISSUE TITLE
Testing - sharing & copy feature

### ISSUE THREAD

**Issue by MAYALURI-ANUSHA** [LanguageTranslationOrg/LanguageTranslationSystem#40]
Sharing and Copy features are to be tested based on the test cases developed by the team

@samaksh-ahuja

**Comment by samaksh-ahuja** [comment]
[testing 2.pdf](https://github.com/user-attachments/files/16279279/testing.2.pdf)
copy and sharing testing pdf

**Comment by samaksh-ahuja** [comment]
[Uploading testing 2.xlsx…]()
