### ISSUE TITLE
Testing - Translation feature

### ISSUE THREAD

**Issue by MAYALURI-ANUSHA** [LanguageTranslationOrg/LanguageTranslationSystem#41]
Translation features should be tested based on test cases developed by the team

@mahitha022 
@nishaverma03

**Comment by nishaverma03** [comment]
https://1drv.ms/x/c/2c2c457d6d774624/ERXQ26wufYdNuVhuXGGxZzoBdqOgYvRdYYQUGrXME7GZyA?e=3YB3lF

Testing of Translation features is done. Getting an error for sharing through mail. Also getting  warning  of "Please Enter English Characters only" sometimes while testing translation features in different languages. The result is in the given link.

**Comment by nishaverma03** [comment]
https://1drv.ms/x/c/2c2c457d6d774624/ERXQ26wufYdNuVhuXGGxZzoBdqOgYvRdYYQUGrXME7GZyA?e=3YB3lF

Testing of Translation features is done and the result is in the excel file according to the test cases of the translation features uploaded in docs folder in word file.

**Comment by nishaverma03** [comment]
Sometimes we are getting extra words in the testing of urdu as a source language and English as a target language.

**Comment by MAYALURI-ANUSHA** [comment]
The report of testing results has been uploaded to the repository.
